<?php
/** @var \KnockOutJS\UIComponent\Block\Demo $block  */
?>

<div id="uic-demo-container" data-bind="scope: 'uicdemo'">
    <!--k ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "#uic-demo-container":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "uicdemo":{
                        "component":"KnockOutJS_UIComponent/js/view/demo",
                        "config":{
                            "template":"KnockOutJS_UIComponent/demo"
                        }
                    }
                }
            }
        }
    }
</script>