<table>
       
       <tr>
           <th scope="col" class="col title">ID</th>
           <th scope="col" class="col title">Path</th>
           
           
       </tr>
       <?php
           $collectionData = $block->getCollection();
        //    var_dump($collectionData);
        //    exit();
           foreach($collectionData as $collection):
       ?>
       <tr>
           <td data-th="ID" ><?php echo $collection->getId(); ?></td>
           <td data-th="Path" ><img src="<?php echo $collection->getPath(); ?>" width="40" 
     height="50" ></td>
           
       </tr>
           
       <?php endforeach; ?>
        
   </table>

