<!DOCTYPE html>
<html>
<body>
    <section class="regular slider">
        <?php
           $collectionData = $block->getCollection();
        //    var_dump($collectionData);
        //    exit();
           foreach($collectionData as $collection):
        ?>

        <div>
            <img src=" <?php echo $collection->getPath(); ?>" width="400" 
     height="500" />
        </div>

       <?php endforeach; ?>
        
        <!-- <div>
            <img src="http://placehold.it/350x300?text=2" />
        </div>
        <div>
            <img src="http://placehold.it/350x300?text=3" />
        </div>
        <div>
            <img src="http://placehold.it/350x300?text=4" />
        </div>
        <div>
            <img src="http://placehold.it/350x300?text=5" />
        </div>
        <div>
            <img src="http://placehold.it/350x300?text=6" />
        </div> -->
    </section>
</body>
</html>